import "@/style/globals.css";
import localFont from 'next/font/local'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// mui
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles'
import { CssBaseline, Grid } from "@mui/material";
import theme from "@/ui/theme";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const myFont = localFont({
  src: '../assets/font/BYekan.ttf',
  display: 'swap',
})
export const metadata = {
  title: "بلاگ ساده من",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={myFont.className}
    >
      <body >
        <AppRouterCacheProvider
          options={{
            key: 'css',
            enableCssLayer: true
          }}
        >
          <ThemeProvider theme={theme}>
            <Grid container>
              <CssBaseline />
              <ToastContainer
                autoClose={2000}
                closeButton={true}
                pauseOnHover={true}
                draggable={true}
              />
              <Navbar />
              {children}
              <Footer />

            </Grid>
          </ThemeProvider>
        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
